<?php
if($this->data):?>
    <?php
    $ico_default="check";
    $state=[0=>'PUBLICADO/HABILITADO',1=>'ARQUIVADO/DESABILITADO'];
    $icons=['title'=>'text-width  ','email'=>'envelope-o','created'=>'calendar','modified'=>'calendar'];
    $ignore=['1'=>'asset_id','2'=>'empresa','3'=>'access','4'=>'codigo','5'=>'id'];
    ?>
    <div class="btn-group stick-top-right">
        <a  href="<?=$this->url("{$this->route}/default",['controller'=>$this->controller,'action'=>'update','id'=>$this->data->getId()]);?>" class="btn btn-icon-toggle btn-success"><i class="md md-edit"></i></a>
        <a  onclick="window.materialadmin.App._deleteItem('<?=$this->url("{$this->route}/default",['controller'=>$this->controller,'action'=>'delete','id'=>$this->data->getId()]);?>')" class="btn btn-icon-toggle btn-danger excluir"><i class="fa fa-trash-o"></i></a>
        <a id="btn-print-item" onclick="window.materialadmin.AppPrint._printItemMelhorMinisterio('<?=$this->url("{$this->route}/default",['controller'=>$this->controller,'action'=>$this->action_print,'id'=>$this->data->getId()])?>')" class="btn btn-icon-toggle btn-warning"><i class="md md-print"></i></a>
    </div>
    <br>
    <ul class="list">
        <?php foreach($this->data->toArray() as $key => $o):
            if(!array_search($key,$ignore)):?>
                <li class="tile">
                    <a class="tile-content ink-reaction">
                        <div class="tile-icon">
                            <?php
                            $icon=$ico_default;
                            if(array_key_exists($key,$icons)):
                                $icon=$icons[$key];
                            endif;
                            if($key=='state'){
                                $o=$state[$o];
                            }
                            if($key=='id'){
                                $o=str_pad($o,11,'0',STR_PAD_LEFT);
                            }
                            ?>

                            <i class="fa fa-<?=$icon;?>"></i>
                        </div>
                        <div class="tile-text">
                            <small><?=$this->translate("FILD_".strtoupper($key)."_LABEL");?></small>
                            <?=$o;?>

                        </div>
                    </a>
                </li>
            <?php
            endif;
        endforeach;?>
    </ul>
<?php else:?>
    <div class="col-lg-12 text-center">
        <h1><span class="text-xxxl text-light"><i class="fa fa-exclamation-circle text-danger"></i></span></h1>
        <h2 class="text-light">Oops! Nenhum Artigo Foi Selecionado</h2>
    </div>
<?php endif;?>