<section class="has-actions style-default-bright">
    <!-- BEGIN INBOX -->
    <div class="section-body">
        <div class="row">
               <!-- BEGIN MAIL COMPOSE -->
            <div class="col-xs-12 col-md-10 col-lg-8 col-md-offset-1 col-lg-offset-2 col-xs-offset-0">
                <h3>#compose#</h3>
                <form method="POST" name="Facebook" id="Manager" enctype="multipart&#x2F;form-data" class="form&#x20;floating-label&#x20;form-validate" accept-charset="utf-8" role="form" action="action-form-do-formulario">


                    <div class="col-xs-12 col-sm-6 col-md-8">
                        <fieldset>
                            <legend>GERAL</legend>
                            #id#
#asset_id#
#codigo#
#empresa#
<div class="row"><div class="col-md-12"><div class="form-group">#app_id#{{app_id}}</div></div></div>
<div class="row"><div class="col-md-12"><div class="form-group">#title#{{title}}</div></div></div>
<div class="row"><div class="col-md-12"><div class="form-group">#site_name#{{site_name}}</div></div></div>
<div class="row"><div class="col-md-12"><div class="form-group">#type#{{type}}</div></div></div>
<div class="row"><div class="col-md-12"><div class="form-group">#description#{{description}}</div></div></div>
#security#

                            <div class="clearfix"></div>
                        </fieldset>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-4">
                        <fieldset>
                            <legend>FORMULARIO DE ADICIONAL</legend>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="row"><div class="col-md-12">
    <div class="img-add images"><label for="images">Imagem/Foto</label> #imagePriview# </div>
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">SELECIONE</span>
            <div class="input-group-content">
                <input type="text" name="images" id="images" title="FILD_IMAGES_DESC" class="images&#x20;form-control" readonly="readonly" value="images&#x2F;2016&#x2F;10&#x2F;2.jpg">
            </div>
													<span class="input-group-addon">
													<i class="fa  fa-picture-o"></i>
													</span>
        </div>
    </div>
    <input type="file" class="atachament" id="atachament" name="atachament">
</div><!--end .form-group --></div>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="col-md-12">
                                    <div class="row"><div class="col-md-12"><div class="form-group">#access#{{access}}</div></div></div>
<div class="row"><div class="col-md-12"><div class="form-group">#state#{{state}}</div></div></div>
<div class="row"><div class="col-md-12"><div class="form-group">
        <div class="input-group" id="">
            <div class="input-group-content">
                #created#
                {{created}}
                
            </div>
            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
        </div>
    </div>
</div></div>
<div class="row"><div class="col-md-12"><div class="form-group">
        <div class="input-group" id="">
            <div class="input-group-content">
                #modified#
                {{modified}}
                
            </div>
            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
        </div>
    </div>
</div></div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </fieldset>
                    </div>


                    <div class="clearfix"></div>

                    <!-- BEGIN SECTION ACTION -->
                    <div class="section-action style-primary">
                        <div class="section-action-row">

                        </div>
                        <div class="section-floating-action-row">
                            #btn-voltar#
                              #comando#

                        </div>
                    </div>
                    </form>
            </div>
        </div>
                <!-- END INBOX -->
                <!-- END SECTION ACTION -->
</section>